"""added missing token_id githubtoken table

Revision ID: 297ade6101bf
Revises: a5b9bdf39779
Create Date: 2024-09-30 00:56:18.477796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297ade6101bf'
down_revision: Union[str, None] = 'a5b9bdf39779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_token', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'github_token', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'github_token', type_='foreignkey')
    op.drop_column('github_token', 'token_id')
    # ### end Alembic commands ###
