"""add webhook information to user

Revision ID: 4e5be165b844
Revises: c7b3793891b2
Create Date: 2024-10-23 12:33:33.432719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5be165b844'
down_revision: Union[str, None] = 'c7b3793891b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_webhook_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gmail_history_id', sa.String(), nullable=True),
    sa.Column('gmail_expiration_date', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_webhook_info_id'), 'gmail_webhook_info', ['id'], unique=False)
    op.drop_column('user', 'gmail_history_id')
    op.drop_column('user', 'gmail_expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gmail_expiration_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('gmail_history_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gmail_webhook_info_id'), table_name='gmail_webhook_info')
    op.drop_table('gmail_webhook_info')
    # ### end Alembic commands ###
