"""add ondelete=CASCADE

Revision ID: 5f3f18e10e82
Revises: fe6a47308e4b
Create Date: 2024-09-30 05:12:09.941893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3f18e10e82'
down_revision: Union[str, None] = 'fe6a47308e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('github_token_token_id_fkey', 'github_token', type_='foreignkey')
    op.create_foreign_key(None, 'github_token', 'token', ['token_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'github_token', type_='foreignkey')
    op.create_foreign_key('github_token_token_id_fkey', 'github_token', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###
