"""gmail history id added ot user model

Revision ID: 95878e6cadb7
Revises: 247ffcd7c22f
Create Date: 2024-10-22 11:42:36.381099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95878e6cadb7'
down_revision: Union[str, None] = '247ffcd7c22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gmail_history_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gmail_history_id')
    # ### end Alembic commands ###
